server:
  port: 8000
eureka:
  instance:
    hostname: localhost
#    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone:  http://${eureka.instance.hostname}:${server.port}/eureka/
